# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleRecorder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ExampleRecorder
pod 'glm', :git => 'https://github.com/maxcampolo/glm.git'
pod 'VideoCore', :git => 'https://github.com/tuananh-vn/VideoCore.git'


pod 'MBProgressHUD'
pod 'CocoaAsyncSocket'
pod 'AFNetworking', '~> 3.0'
pod 'Firebase/Messaging'
pod 'Firebase/Core'
  target 'ExampleRecorderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
